# Generated by Django 6.0.3 on 2026-03-29 03:56

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='统编代码')),
                ('drug_category', models.CharField(choices=[('化学药品', '化学药品'), ('生物制品', '生物制品'), ('中成药', '中成药')], max_length=50, verbose_name='药品分类')),
                ('generic_name', models.CharField(max_length=200, verbose_name='通用名')),
                ('catalog_dosage_form', models.CharField(blank=True, max_length=100, verbose_name='目录剂型')),
                ('spec_package', models.CharField(blank=True, max_length=200, verbose_name='规格包装')),
                ('content', models.CharField(blank=True, max_length=50, verbose_name='含量')),
                ('content_unit', models.CharField(blank=True, max_length=20, verbose_name='含量单位')),
                ('volume', models.CharField(blank=True, max_length=50, verbose_name='装量')),
                ('volume_unit', models.CharField(blank=True, max_length=20, verbose_name='装量单位')),
                ('quantity', models.CharField(blank=True, max_length=50, verbose_name='计价数量')),
                ('quantity_unit', models.CharField(blank=True, max_length=20, verbose_name='计价数量单位')),
                ('usage_days', models.CharField(blank=True, max_length=50, verbose_name='服用天数')),
                ('standard_holder', models.CharField(blank=True, max_length=200, verbose_name='标化持有人')),
                ('catalog_name', models.CharField(blank=True, max_length=200, verbose_name='医保目录名')),
                ('special_note', models.CharField(blank=True, max_length=200, verbose_name='特殊标注')),
                ('network_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='挂网价')),
                ('anchor_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='锚点价格')),
                ('is_standard', models.BooleanField(default=False, verbose_name='是否标准品')),
                ('standard_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='差比价')),
                ('price_diff', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='价差对比')),
            ],
            options={
                'verbose_name': '药品',
                'verbose_name_plural': '药品',
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='权限名称')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='权限编码')),
                ('module', models.CharField(max_length=50, verbose_name='所属模块')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
            ],
            options={
                'verbose_name': '权限',
                'verbose_name_plural': '权限',
            },
        ),
        migrations.CreateModel(
            name='PharmaceuticalCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_code', models.CharField(max_length=50, unique=True, verbose_name='机构编码')),
                ('company_name', models.CharField(max_length=200, verbose_name='企业名称')),
                ('contact_person', models.CharField(blank=True, max_length=100, verbose_name='联系人')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='电话')),
                ('address', models.CharField(blank=True, max_length=300, verbose_name='地址')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '药企',
                'verbose_name_plural': '药企',
            },
        ),
        migrations.CreateModel(
            name='Pharmacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pharmacy_code', models.CharField(max_length=50, unique=True, verbose_name='药店编码')),
                ('pharmacy_name', models.CharField(max_length=200, verbose_name='药店名称')),
                ('medical_insurance_code', models.CharField(max_length=50, verbose_name='医保编码')),
                ('district', models.CharField(max_length=50, verbose_name='区县')),
                ('address', models.CharField(blank=True, max_length=300, verbose_name='地址')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='电话')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '药店',
                'verbose_name_plural': '药店',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('user_type', models.CharField(choices=[('admin', '系统管理员'), ('manager', '部门经理'), ('sales', '销售人员')], max_length=20, verbose_name='用户类型')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='联系电话')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='客户名称')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='客户编码')),
                ('industry', models.CharField(blank=True, max_length=100, verbose_name='行业')),
                ('level', models.CharField(blank=True, max_length=50, verbose_name='客户级别')),
                ('status', models.CharField(choices=[('潜在', '潜在'), ('跟进中', '跟进中'), ('商机', '商机'), ('成交', '成交'), ('流失', '流失')], default='潜在', max_length=20, verbose_name='状态')),
                ('source', models.CharField(blank=True, choices=[('推荐', '推荐'), ('电话营销', '电话营销'), ('展会', '展会'), ('网络推广', '网络推广'), ('其他', '其他')], max_length=20, verbose_name='客户来源')),
                ('address', models.CharField(blank=True, max_length=300, verbose_name='地址')),
                ('website', models.CharField(blank=True, max_length=200, verbose_name='网站')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_customers', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_customers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '客户',
                'verbose_name_plural': '客户',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='姓名')),
                ('position', models.CharField(blank=True, max_length=100, verbose_name='职位')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='电话')),
                ('mobile', models.CharField(blank=True, max_length=20, verbose_name='手机')),
                ('email', models.CharField(blank=True, max_length=100, verbose_name='邮箱')),
                ('is_primary', models.BooleanField(default=False, verbose_name='是否主要联系人')),
                ('description', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='core.customer')),
            ],
            options={
                'verbose_name': '联系人',
                'verbose_name_plural': '联系人',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='部门名称')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='部门编码')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_depts', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.department')),
            ],
            options={
                'verbose_name': '部门',
                'verbose_name_plural': '部门',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='core.department'),
        ),
        migrations.CreateModel(
            name='CompanyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('declared_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='申报价')),
                ('record_date', models.DateField(verbose_name='数据年月')),
                ('status', models.CharField(choices=[('正常', '正常'), ('异常', '异常'), ('待整改', '待整改'), ('已提交', '已提交'), ('待审核', '待审核'), ('审核通过', '审核通过'), ('审核不通过', '审核不通过')], default='已提交', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_records', to='core.drug')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='core.pharmaceuticalcompany')),
            ],
            options={
                'verbose_name': '药企申报价',
                'verbose_name_plural': '药企申报价',
            },
        ),
        migrations.CreateModel(
            name='PharmacyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='备案价')),
                ('record_date', models.DateField(verbose_name='数据年月')),
                ('status', models.CharField(choices=[('正常', '正常'), ('异常', '异常'), ('待整改', '待整改'), ('已提交', '已提交'), ('待审核', '待审核'), ('审核通过', '审核通过'), ('审核不通过', '审核不通过')], default='已提交', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pharmacy_records', to='core.drug')),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='core.pharmacy')),
            ],
            options={
                'verbose_name': '药店备案价',
                'verbose_name_plural': '药店备案价',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='项目名称')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='项目编码')),
                ('budget', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='预算')),
                ('status', models.CharField(choices=[('草稿', '草稿'), ('已提交', '已提交'), ('已立项', '已立项'), ('进行中', '进行列'), ('已完成', '已完成'), ('已取消', '已取消')], default='草稿', max_length=20, verbose_name='状态')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='开始日期')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='结束日期')),
                ('description', models.TextField(blank=True, verbose_name='项目描述')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_projects', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='core.customer')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '项目',
                'verbose_name_plural': '项目',
            },
        ),
        migrations.CreateModel(
            name='FollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follow_type', models.CharField(choices=[('电话', '电话'), ('拜访', '拜访'), ('邮件', '邮件'), ('会议', '会议'), ('其他', '其他')], default='电话', max_length=20, verbose_name='跟进方式')),
                ('subject', models.CharField(max_length=200, verbose_name='跟进主题')),
                ('content', models.TextField(verbose_name='跟进内容')),
                ('status', models.CharField(choices=[('待处理', '待处理'), ('进行中', '进行中'), ('已完成', '已完成'), ('已取消', '已取消')], default='待处理', max_length=20, verbose_name='状态')),
                ('next_action', models.TextField(blank=True, verbose_name='下一步行动')),
                ('next_date', models.DateField(blank=True, null=True, verbose_name='下次跟进日期')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_ups', to='core.customer')),
                ('follower', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='follow_ups', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='follow_ups', to='core.project')),
            ],
            options={
                'verbose_name': '跟进记录',
                'verbose_name_plural': '跟进记录',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='角色名称')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='角色编码')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('permissions', models.ManyToManyField(blank=True, related_name='roles', to='core.permission')),
            ],
            options={
                'verbose_name': '角色',
                'verbose_name_plural': '角色',
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=200, verbose_name='出差目的地')),
                ('purpose', models.TextField(verbose_name='出差目的')),
                ('start_date', models.DateField(verbose_name='开始日期')),
                ('end_date', models.DateField(verbose_name='结束日期')),
                ('status', models.CharField(choices=[('草稿', '草稿'), ('已提交', '已提交'), ('已审批', '已审批'), ('已拒绝', '已拒绝'), ('已完成', '已完成')], default='草稿', max_length=20, verbose_name='状态')),
                ('estimated_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='预计费用')),
                ('actual_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='实际费用')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trips', to='core.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '出差申请',
                'verbose_name_plural': '出差申请',
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_type', models.CharField(choices=[('差旅费', '差旅费'), ('招待费', '招待费'), ('通讯费', '通讯费'), ('办公费', '办公费'), ('其他', '其他')], max_length=20, verbose_name='费用类型')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='金额')),
                ('expense_date', models.DateField(verbose_name='费用日期')),
                ('description', models.TextField(verbose_name='费用说明')),
                ('receipt', models.FileField(blank=True, null=True, upload_to='receipts/', verbose_name='收据')),
                ('status', models.CharField(choices=[('草稿', '草稿'), ('已提交', '已提交'), ('已审批', '已审批'), ('已拒绝', '已拒绝'), ('已报销', '已报销')], default='草稿', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='core.project')),
                ('trip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='core.trip')),
            ],
            options={
                'verbose_name': '业务费用',
                'verbose_name_plural': '业务费用',
            },
        ),
    ]
