# Generated by Django 6.0.3 on 2026-03-29 03:33

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='统编代码')),
                ('drug_category', models.CharField(choices=[('化学药品', '化学药品'), ('生物制品', '生物制品'), ('中成药', '中成药')], max_length=50, verbose_name='药品分类')),
                ('generic_name', models.CharField(max_length=200, verbose_name='通用名')),
                ('catalog_dosage_form', models.CharField(blank=True, max_length=100, verbose_name='目录剂型')),
                ('spec_package', models.CharField(blank=True, max_length=200, verbose_name='规格包装')),
                ('content', models.CharField(blank=True, max_length=50, verbose_name='含量')),
                ('content_unit', models.CharField(blank=True, max_length=20, verbose_name='含量单位')),
                ('volume', models.CharField(blank=True, max_length=50, verbose_name='装量')),
                ('volume_unit', models.CharField(blank=True, max_length=20, verbose_name='装量单位')),
                ('quantity_unit', models.CharField(blank=True, max_length=20, verbose_name='计价数量单位')),
                ('quantity', models.CharField(blank=True, max_length=50, verbose_name='计价数量')),
                ('usage_days', models.CharField(blank=True, max_length=50, verbose_name='服用天数')),
                ('standard_holder', models.CharField(blank=True, max_length=200, verbose_name='标化持有人')),
                ('catalog_name', models.CharField(blank=True, max_length=200, verbose_name='医保目录名')),
                ('special_note', models.CharField(blank=True, max_length=200, verbose_name='特殊标注')),
                ('network_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='挂网价')),
                ('anchor_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='锚点价格')),
                ('anchor_price_ratio', models.DecimalField(decimal_places=2, default=1.0, max_digits=5, verbose_name='锚点价格倍率')),
                ('is_standard', models.BooleanField(default=False, verbose_name='是否标准品')),
                ('standard_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='差比价')),
                ('price_diff', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='价差对比')),
                ('unit_value', models.DecimalField(decimal_places=6, default=0, max_digits=20, verbose_name='单体差比值')),
            ],
            options={
                'verbose_name': '药品',
                'verbose_name_plural': '药品',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('user_type', models.CharField(choices=[('yaoshisuo', '药事所'), ('yaodian', '药店'), ('yaoqi', '药企'), ('quxian', '区县医保局')], max_length=20, verbose_name='用户类型')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='联系电话')),
                ('district', models.CharField(blank=True, max_length=50, verbose_name='所属区县')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='PharmaceuticalCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_code', models.CharField(max_length=50, unique=True, verbose_name='机构编码')),
                ('company_name', models.CharField(max_length=200, verbose_name='企业名称')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '药企',
                'verbose_name_plural': '药企',
            },
        ),
        migrations.CreateModel(
            name='CompanyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('declared_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='申报价')),
                ('record_date', models.DateField(verbose_name='数据年月')),
                ('status', models.CharField(choices=[('正常', '正常'), ('异常', '异常'), ('待整改', '待整改'), ('已提交', '已提交'), ('待审核', '待审核'), ('审核通过', '审核通过'), ('审核不通过', '审核不通过')], default='已提交', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_reviews', to=settings.AUTH_USER_MODEL)),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_records', to='core.drug')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='core.pharmaceuticalcompany')),
            ],
            options={
                'verbose_name': '药企申报价',
                'verbose_name_plural': '药企申报价',
            },
        ),
        migrations.CreateModel(
            name='Pharmacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pharmacy_code', models.CharField(max_length=50, unique=True, verbose_name='药店编码')),
                ('pharmacy_name', models.CharField(max_length=200, verbose_name='药店名称')),
                ('medical_insurance_code', models.CharField(max_length=50, verbose_name='医保编码')),
                ('district', models.CharField(max_length=50, verbose_name='注册区县')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pharmacies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '药店',
                'verbose_name_plural': '药店',
            },
        ),
        migrations.CreateModel(
            name='PharmacyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='备案价')),
                ('record_date', models.DateField(verbose_name='数据年月')),
                ('status', models.CharField(choices=[('正常', '正常'), ('异常', '异常'), ('待整改', '待整改'), ('已提交', '已提交'), ('待审核', '待审核'), ('审核通过', '审核通过'), ('审核不通过', '审核不通过')], default='已提交', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pharmacy_records', to='core.drug')),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='core.pharmacy')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pharmacy_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '药店备案价',
                'verbose_name_plural': '药店备案价',
            },
        ),
    ]
