# Generated by Django 5.2.12 on 2026-04-03 14:53

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_companyrecord_id_alter_contact_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='区县名称')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='区县编码')),
            ],
            options={
                'verbose_name': '区县',
                'verbose_name_plural': '区县',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='medical_insurance_code',
            field=models.CharField(blank=True, max_length=50, verbose_name='医保编码'),
        ),
        migrations.AddField(
            model_name='user',
            name='organization',
            field=models.CharField(blank=True, max_length=200, verbose_name='所属机构'),
        ),
        migrations.AlterField(
            model_name='companyrecord',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='department',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='drug',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='followup',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='pharmaceuticalcompany',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='pharmacy',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='pharmacyrecord',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='role',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('admin', '系统管理员'), ('supervisor', '药事所监督科'), ('drug_section', '药事所药品科'), ('pharmacy', '药店'), ('company', '药企'), ('district', '区县医保局')], max_length=20, verbose_name='用户类型'),
        ),
        migrations.CreateModel(
            name='AnchorPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anchor_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='锚点价格')),
                ('adjust_ratio', models.DecimalField(decimal_places=2, default=Decimal('1.0'), max_digits=5, verbose_name='调整倍率')),
                ('target_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='治理价格')),
                ('record_date', models.DateField(verbose_name='数据年月')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anchor_prices', to='core.drug')),
            ],
            options={
                'verbose_name': '锚点价格',
                'verbose_name_plural': '锚点价格',
            },
        ),
        migrations.CreateModel(
            name='CompanyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='core.pharmaceuticalcompany')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '药企用户',
                'verbose_name_plural': '药企用户',
            },
        ),
        migrations.CreateModel(
            name='DrugPriceReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='原价格')),
                ('proposed_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='整改价格')),
                ('status', models.CharField(choices=[('正常', '正常'), ('异常', '异常'), ('待整改', '待整改'), ('已提交', '已提交'), ('待审核', '待审核'), ('审核通过', '审核通过'), ('审核不通过', '审核不通过')], default='待整改', max_length=20, verbose_name='审核状态')),
                ('comment', models.TextField(blank=True, verbose_name='审核意见')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_reviews', to='core.drug')),
                ('reviewer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='审核人')),
            ],
            options={
                'verbose_name': '药品挂网价审核',
                'verbose_name_plural': '药品挂网价审核',
            },
        ),
        migrations.CreateModel(
            name='PharmacyRecordReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('正常', '正常'), ('异常', '异常'), ('待整改', '待整改'), ('已提交', '已提交'), ('待审核', '待审核'), ('审核通过', '审核通过'), ('审核不通过', '审核不通过')], default='待审核', max_length=20, verbose_name='审核状态')),
                ('comment', models.TextField(blank=True, verbose_name='审核意见')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('district', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.district', verbose_name='审核区县')),
                ('pharmacy_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='core.pharmacyrecord')),
                ('reviewer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='审核人')),
            ],
            options={
                'verbose_name': '药店备案价审核',
                'verbose_name_plural': '药店备案价审核',
            },
        ),
        migrations.CreateModel(
            name='PharmacyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='core.pharmacy')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pharmacy_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '药店用户',
                'verbose_name_plural': '药店用户',
            },
        ),
    ]
